name: EcoImpacto

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  

    - name: Restore dependencies
      run: dotnet restore ./Back-end/EcoImpacto.API/EcoImpacto.API.csproj  

    - name: Build
      run: dotnet build ./Back-end/EcoImpacto.API/EcoImpacto.API.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./Back-end/EcoImpacto.API/EcoImpacto.API.csproj --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deploying the application..."
      # Adicionar o deploy
