name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Use a versão correta do .NET que você está usando

    - name: Restore dependencies
      run: dotnet restore Back-end/EcoImpacto.sln

    - name: Build the solution
      run: dotnet build Back-end/EcoImpacto.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test Back-end/EcoImpacto.sln --no-restore --verbosity normal
